# Covered Call Strategy Configuration
# Filename: covered_call.yaml (with underscore to match README examples)

strategy:
  name: "CoveredCall"
  description: "Sell covered calls against long underlying positions"
  
  parameters:
    # Target delta range for call selection
    min_delta: 0.25
    max_delta: 0.35
    
    # Days to expiry range
    min_dte: 30
    max_dte: 45
    
    # Roll criteria
    roll_at_pnl_percent: 50.0  # Roll when 50% profit achieved
    roll_at_dte: 21            # Roll when 21 DTE reached
    
    # Position sizing
    lot_size: 100              # Shares per lot
    max_positions: 10          # Maximum concurrent positions

# Risk management
risk:
  max_portfolio_delta: 1000   # Maximum portfolio delta exposure
  max_single_position: 10000  # Maximum single position value
  max_daily_loss: 5000        # Maximum daily loss limit
  
# Execution settings
execution:
  order_type: "LIMIT"
  price_improvement: 0.01     # Try for $0.01 price improvement
  timeout_seconds: 30
  
# Market data
market_data:
  symbols: ["SPY", "QQQ", "IWM"]
  tick_size: 0.01
  
# Backtesting
backtest:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_capital: 100000
  commission_per_contract: 0.65
  
# Reporting
reporting:
  output_path: "artifacts/covered_call"
  generate_plots: true
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"